search_string: 'A488_*.ptu'
filetype: 'PTU'
binning: 4
ch1_suffix: '_green_s.txt'
ch2_suffix: '_green_p.txt'
channel_number_ch1: [0]
channel_number_ch2: [2]
make_plots: True
display_plot: False
jordi: True
anisotropy: True
g_factor: 0.98