search_string: 'DNA*.ptu'
filetype: 'PTU'
PIE_suffix: '_PIE.cor'
FRET_suffix: '_FRET.cor'
green_prompt_suffix: '_gp.cor'
red_prompt_suffix: '_rp.cor'
red_delay_suffix: '_rd.cor'
green_channel_ch1: 0
green_channel_ch2: 2
red_channel_ch1: 1
red_channel_ch2: 3
n_casc: 25
n_bins: 9
n_chunks: 3
make_plots: True
display_plot: False